/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import AccesoDatos.MeseroData;
import Entidades.PanelPersonalizado;
import static Vistas.MenuPrincipal.Escritorio;
import javax.swing.JOptionPane;
    
/**
 *
 * @author nstut
 */
public class MeserosContrasenia extends javax.swing.JInternalFrame {
    private int id_mesero;
    PanelPersonalizado panel = new PanelPersonalizado("/imagenes/fondoInternal2.jpg");
    /**
     * Creates new form MeserosContrasenia
     */
    public MeserosContrasenia(int id_mesero) {
        this.id_mesero = id_mesero;
        this.setContentPane(panel);
        initComponents();
        cargarContrasenia();
        this.setLocation(60, 150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlMesero = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtpContraActual = new javax.swing.JTextPane();
        jtfContraNueva = new javax.swing.JTextField();
        jbCambiar = new javax.swing.JButton();
        jbVolver = new javax.swing.JButton();

        setClosable(true);
        setForeground(java.awt.Color.white);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jlMesero.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        jlMesero.setForeground(java.awt.Color.white);
        jlMesero.setText("Gestion de contraseña");

        jLabel2.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Contraseña actual:");

        jLabel3.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Nueva contraseña:");

        jtpContraActual.setEditable(false);
        jtpContraActual.setBackground(new java.awt.Color(40, 40, 40));
        jtpContraActual.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        jtpContraActual.setForeground(new java.awt.Color(255, 255, 255));
        jtpContraActual.setPreferredSize(new java.awt.Dimension(6, 30));
        jScrollPane1.setViewportView(jtpContraActual);

        jtfContraNueva.setBackground(new java.awt.Color(40, 40, 40));
        jtfContraNueva.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        jtfContraNueva.setForeground(new java.awt.Color(255, 255, 255));
        jtfContraNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfContraNuevaActionPerformed(evt);
            }
        });

        jbCambiar.setBackground(new java.awt.Color(0, 153, 255));
        jbCambiar.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        jbCambiar.setForeground(new java.awt.Color(255, 255, 255));
        jbCambiar.setText("Cambiar");
        jbCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCambiarActionPerformed(evt);
            }
        });

        jbVolver.setBackground(new java.awt.Color(40, 40, 40));
        jbVolver.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        jbVolver.setForeground(new java.awt.Color(255, 255, 255));
        jbVolver.setText("Volver");
        jbVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jbCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jbVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jtfContraNueva, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jlMesero)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlMesero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfContraNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfContraNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfContraNuevaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfContraNuevaActionPerformed

    private void jbCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCambiarActionPerformed
        MeseroData md = new MeseroData();
        String contra = jtfContraNueva.getText();
        if(contra.length() < 3 || contra.length() > 8) {
            JOptionPane.showMessageDialog(this, "La contraseña debe tener entre 3 a 8 caracteres.");
        } else {
            md.actualizarContrasenia(id_mesero, contra);
            this.dispose();
        }
    }//GEN-LAST:event_jbCambiarActionPerformed

    private void jbVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolverActionPerformed
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jbVolverActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        Escritorio.removeAll();
        Escritorio.repaint();
        MeserosGestionar mg = new MeserosGestionar();
        mg.setVisible(true);
        Escritorio.add(mg);
        Escritorio.moveToFront(mg);
    }//GEN-LAST:event_formInternalFrameClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCambiar;
    private javax.swing.JButton jbVolver;
    private javax.swing.JLabel jlMesero;
    private javax.swing.JTextField jtfContraNueva;
    private javax.swing.JTextPane jtpContraActual;
    // End of variables declaration//GEN-END:variables

private void cargarContrasenia () {
    MeseroData md = new MeseroData();
    String contra = md.getMesero(id_mesero).getContrasenia();
    jtpContraActual.setText(contra);
    
    String nombre = md.getMesero(id_mesero).getNombre();
    String apellido = md.getMesero(id_mesero).getApellido();
     jlMesero.setText("Gestion de contraseña de "+nombre+" "+apellido);
}            
}
